/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Context
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContextTests
    {
        // TODO uncomment below to declare an instance variable for Context
        //private Context instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Context
            //instance = new Context();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Context
        /// </summary>
        [Test]
        public void ContextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Context
            //Assert.IsInstanceOfType<Context> (instance, "variable 'instance' is a Context");
        }

        /// <summary>
        /// Test the property 'TenantSelectionPageUrl'
        /// </summary>
        [Test]
        public void TenantSelectionPageUrlTest()
        {
            // TODO unit test for the property 'TenantSelectionPageUrl'
        }
        /// <summary>
        /// Test the property 'UserHasMultipleEntitlements'
        /// </summary>
        [Test]
        public void UserHasMultipleEntitlementsTest()
        {
            // TODO unit test for the property 'UserHasMultipleEntitlements'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'UserEmail'
        /// </summary>
        [Test]
        public void UserEmailTest()
        {
            // TODO unit test for the property 'UserEmail'
        }
        /// <summary>
        /// Test the property 'TenantAlias'
        /// </summary>
        [Test]
        public void TenantAliasTest()
        {
            // TODO unit test for the property 'TenantAlias'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
