/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EnrichedVersion
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnrichedVersionTests
    {
        // TODO uncomment below to declare an instance variable for EnrichedVersion
        //private EnrichedVersion instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnrichedVersion
            //instance = new EnrichedVersion();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnrichedVersion
        /// </summary>
        [Test]
        public void EnrichedVersionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnrichedVersion
            //Assert.IsInstanceOfType<EnrichedVersion> (instance, "variable 'instance' is a EnrichedVersion");
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'LastHourUptime'
        /// </summary>
        [Test]
        public void LastHourUptimeTest()
        {
            // TODO unit test for the property 'LastHourUptime'
        }
        /// <summary>
        /// Test the property 'LastDayUptime'
        /// </summary>
        [Test]
        public void LastDayUptimeTest()
        {
            // TODO unit test for the property 'LastDayUptime'
        }
        /// <summary>
        /// Test the property 'LastMonthUptime'
        /// </summary>
        [Test]
        public void LastMonthUptimeTest()
        {
            // TODO unit test for the property 'LastMonthUptime'
        }
        /// <summary>
        /// Test the property 'PreviousVersion'
        /// </summary>
        [Test]
        public void PreviousVersionTest()
        {
            // TODO unit test for the property 'PreviousVersion'
        }
        /// <summary>
        /// Test the property 'Components'
        /// </summary>
        [Test]
        public void ComponentsTest()
        {
            // TODO unit test for the property 'Components'
        }
        /// <summary>
        /// Test the property 'Workloads'
        /// </summary>
        [Test]
        public void WorkloadsTest()
        {
            // TODO unit test for the property 'Workloads'
        }
        /// <summary>
        /// Test the property 'CustomProperties'
        /// </summary>
        [Test]
        public void CustomPropertiesTest()
        {
            // TODO unit test for the property 'CustomProperties'
        }
        /// <summary>
        /// Test the property 'ArchiveDownload'
        /// </summary>
        [Test]
        public void ArchiveDownloadTest()
        {
            // TODO unit test for the property 'ArchiveDownload'
        }
        /// <summary>
        /// Test the property 'FilesDownload'
        /// </summary>
        [Test]
        public void FilesDownloadTest()
        {
            // TODO unit test for the property 'FilesDownload'
        }
        /// <summary>
        /// Test the property 'ManifestDownload'
        /// </summary>
        [Test]
        public void ManifestDownloadTest()
        {
            // TODO unit test for the property 'ManifestDownload'
        }
        /// <summary>
        /// Test the property 'Tenants'
        /// </summary>
        [Test]
        public void TenantsTest()
        {
            // TODO unit test for the property 'Tenants'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Test]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Stage'
        /// </summary>
        [Test]
        public void StageTest()
        {
            // TODO unit test for the property 'Stage'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Test]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }
        /// <summary>
        /// Test the property 'EnableStickySessions'
        /// </summary>
        [Test]
        public void EnableStickySessionsTest()
        {
            // TODO unit test for the property 'EnableStickySessions'
        }
        /// <summary>
        /// Test the property 'EnableSessionReplication'
        /// </summary>
        [Test]
        public void EnableSessionReplicationTest()
        {
            // TODO unit test for the property 'EnableSessionReplication'
        }
        /// <summary>
        /// Test the property 'EnableSslEnforcement'
        /// </summary>
        [Test]
        public void EnableSslEnforcementTest()
        {
            // TODO unit test for the property 'EnableSslEnforcement'
        }
        /// <summary>
        /// Test the property 'LoadBalancerUrlConfiguration'
        /// </summary>
        [Test]
        public void LoadBalancerUrlConfigurationTest()
        {
            // TODO unit test for the property 'LoadBalancerUrlConfiguration'
        }
        /// <summary>
        /// Test the property 'InMaintenance'
        /// </summary>
        [Test]
        public void InMaintenanceTest()
        {
            // TODO unit test for the property 'InMaintenance'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
