/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Apiv1LogOverridesNotification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Apiv1LogOverridesNotificationTests
    {
        // TODO uncomment below to declare an instance variable for Apiv1LogOverridesNotification
        //private Apiv1LogOverridesNotification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Apiv1LogOverridesNotification
            //instance = new Apiv1LogOverridesNotification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Apiv1LogOverridesNotification
        /// </summary>
        [Test]
        public void Apiv1LogOverridesNotificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Apiv1LogOverridesNotification
            //Assert.IsInstanceOfType<Apiv1LogOverridesNotification> (instance, "variable 'instance' is a Apiv1LogOverridesNotification");
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Minutes'
        /// </summary>
        [Test]
        public void MinutesTest()
        {
            // TODO unit test for the property 'Minutes'
        }

    }

}
