/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Apiv1ComponentsEnvironmentVariables
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Apiv1ComponentsEnvironmentVariablesTests
    {
        // TODO uncomment below to declare an instance variable for Apiv1ComponentsEnvironmentVariables
        //private Apiv1ComponentsEnvironmentVariables instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Apiv1ComponentsEnvironmentVariables
            //instance = new Apiv1ComponentsEnvironmentVariables();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Apiv1ComponentsEnvironmentVariables
        /// </summary>
        [Test]
        public void Apiv1ComponentsEnvironmentVariablesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Apiv1ComponentsEnvironmentVariables
            //Assert.IsInstanceOfType<Apiv1ComponentsEnvironmentVariables> (instance, "variable 'instance' is a Apiv1ComponentsEnvironmentVariables");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
