/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Apiv1ComponentsScalingSchedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Apiv1ComponentsScalingScheduleTests
    {
        // TODO uncomment below to declare an instance variable for Apiv1ComponentsScalingSchedule
        //private Apiv1ComponentsScalingSchedule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Apiv1ComponentsScalingSchedule
            //instance = new Apiv1ComponentsScalingSchedule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Apiv1ComponentsScalingSchedule
        /// </summary>
        [Test]
        public void Apiv1ComponentsScalingScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Apiv1ComponentsScalingSchedule
            //Assert.IsInstanceOfType<Apiv1ComponentsScalingSchedule> (instance, "variable 'instance' is a Apiv1ComponentsScalingSchedule");
        }

        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Test]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'InstanceCount'
        /// </summary>
        [Test]
        public void InstanceCountTest()
        {
            // TODO unit test for the property 'InstanceCount'
        }

    }

}
