/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Application
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApplicationTests
    {
        // TODO uncomment below to declare an instance variable for Application
        //private Application instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Application
            //instance = new Application();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Application
        /// </summary>
        [Test]
        public void ApplicationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Application
            //Assert.IsInstanceOfType<Application> (instance, "variable 'instance' is a Application");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Test]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'CurrentVersion'
        /// </summary>
        [Test]
        public void CurrentVersionTest()
        {
            // TODO unit test for the property 'CurrentVersion'
        }
        /// <summary>
        /// Test the property 'TransitioningVersion'
        /// </summary>
        [Test]
        public void TransitioningVersionTest()
        {
            // TODO unit test for the property 'TransitioningVersion'
        }
        /// <summary>
        /// Test the property 'UiAllocatedCpuMhz'
        /// </summary>
        [Test]
        public void UiAllocatedCpuMhzTest()
        {
            // TODO unit test for the property 'UiAllocatedCpuMhz'
        }
        /// <summary>
        /// Test the property 'DbAllocatedCpuMhz'
        /// </summary>
        [Test]
        public void DbAllocatedCpuMhzTest()
        {
            // TODO unit test for the property 'DbAllocatedCpuMhz'
        }
        /// <summary>
        /// Test the property 'SvcAllocatedCpuMhz'
        /// </summary>
        [Test]
        public void SvcAllocatedCpuMhzTest()
        {
            // TODO unit test for the property 'SvcAllocatedCpuMhz'
        }
        /// <summary>
        /// Test the property 'WarAllocatedCpuMhz'
        /// </summary>
        [Test]
        public void WarAllocatedCpuMhzTest()
        {
            // TODO unit test for the property 'WarAllocatedCpuMhz'
        }
        /// <summary>
        /// Test the property 'LinuxServiceAllocatedCpuMhz'
        /// </summary>
        [Test]
        public void LinuxServiceAllocatedCpuMhzTest()
        {
            // TODO unit test for the property 'LinuxServiceAllocatedCpuMhz'
        }
        /// <summary>
        /// Test the property 'UiAllocatedMemoryMb'
        /// </summary>
        [Test]
        public void UiAllocatedMemoryMbTest()
        {
            // TODO unit test for the property 'UiAllocatedMemoryMb'
        }
        /// <summary>
        /// Test the property 'DbAllocatedMemoryMb'
        /// </summary>
        [Test]
        public void DbAllocatedMemoryMbTest()
        {
            // TODO unit test for the property 'DbAllocatedMemoryMb'
        }
        /// <summary>
        /// Test the property 'SvcAllocatedMemoryMb'
        /// </summary>
        [Test]
        public void SvcAllocatedMemoryMbTest()
        {
            // TODO unit test for the property 'SvcAllocatedMemoryMb'
        }
        /// <summary>
        /// Test the property 'WarAllocatedMemoryMb'
        /// </summary>
        [Test]
        public void WarAllocatedMemoryMbTest()
        {
            // TODO unit test for the property 'WarAllocatedMemoryMb'
        }
        /// <summary>
        /// Test the property 'LinuxServiceAllocatedMemoryMb'
        /// </summary>
        [Test]
        public void LinuxServiceAllocatedMemoryMbTest()
        {
            // TODO unit test for the property 'LinuxServiceAllocatedMemoryMb'
        }
        /// <summary>
        /// Test the property 'AllocatedStorageMb'
        /// </summary>
        [Test]
        public void AllocatedStorageMbTest()
        {
            // TODO unit test for the property 'AllocatedStorageMb'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
