/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DebugConnection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DebugConnectionTests
    {
        // TODO uncomment below to declare an instance variable for DebugConnection
        //private DebugConnection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DebugConnection
            //instance = new DebugConnection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DebugConnection
        /// </summary>
        [Test]
        public void DebugConnectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DebugConnection
            //Assert.IsInstanceOfType<DebugConnection> (instance, "variable 'instance' is a DebugConnection");
        }

        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Test]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Test]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'Fqdn'
        /// </summary>
        [Test]
        public void FqdnTest()
        {
            // TODO unit test for the property 'Fqdn'
        }

    }

}
