/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeployedAddOn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeployedAddOnTests
    {
        // TODO uncomment below to declare an instance variable for DeployedAddOn
        //private DeployedAddOn instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeployedAddOn
            //instance = new DeployedAddOn();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeployedAddOn
        /// </summary>
        [Test]
        public void DeployedAddOnInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeployedAddOn
            //Assert.IsInstanceOfType<DeployedAddOn> (instance, "variable 'instance' is a DeployedAddOn");
        }

        /// <summary>
        /// Test the property 'DeployTime'
        /// </summary>
        [Test]
        public void DeployTimeTest()
        {
            // TODO unit test for the property 'DeployTime'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Test]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'ConnectionData'
        /// </summary>
        [Test]
        public void ConnectionDataTest()
        {
            // TODO unit test for the property 'ConnectionData'
        }
        /// <summary>
        /// Test the property 'AddOn'
        /// </summary>
        [Test]
        public void AddOnTest()
        {
            // TODO unit test for the property 'AddOn'
        }
        /// <summary>
        /// Test the property 'InstanceAlias'
        /// </summary>
        [Test]
        public void InstanceAliasTest()
        {
            // TODO unit test for the property 'InstanceAlias'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
