/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EnrichedComponentModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnrichedComponentModelTests
    {
        // TODO uncomment below to declare an instance variable for EnrichedComponentModel
        //private EnrichedComponentModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnrichedComponentModel
            //instance = new EnrichedComponentModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnrichedComponentModel
        /// </summary>
        [Test]
        public void EnrichedComponentModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnrichedComponentModel
            //Assert.IsInstanceOfType<EnrichedComponentModel> (instance, "variable 'instance' is a EnrichedComponentModel");
        }

        /// <summary>
        /// Test the property 'PipelineMode'
        /// </summary>
        [Test]
        public void PipelineModeTest()
        {
            // TODO unit test for the property 'PipelineMode'
        }
        /// <summary>
        /// Test the property 'EnvironmentVariables'
        /// </summary>
        [Test]
        public void EnvironmentVariablesTest()
        {
            // TODO unit test for the property 'EnvironmentVariables'
        }
        /// <summary>
        /// Test the property 'SystemProperties'
        /// </summary>
        [Test]
        public void SystemPropertiesTest()
        {
            // TODO unit test for the property 'SystemProperties'
        }
        /// <summary>
        /// Test the property 'Certificates'
        /// </summary>
        [Test]
        public void CertificatesTest()
        {
            // TODO unit test for the property 'Certificates'
        }
        /// <summary>
        /// Test the property 'Runtime'
        /// </summary>
        [Test]
        public void RuntimeTest()
        {
            // TODO unit test for the property 'Runtime'
        }
        /// <summary>
        /// Test the property 'LogPattern'
        /// </summary>
        [Test]
        public void LogPatternTest()
        {
            // TODO unit test for the property 'LogPattern'
        }
        /// <summary>
        /// Test the property 'Container'
        /// </summary>
        [Test]
        public void ContainerTest()
        {
            // TODO unit test for the property 'Container'
        }
        /// <summary>
        /// Test the property 'JmxEnabled'
        /// </summary>
        [Test]
        public void JmxEnabledTest()
        {
            // TODO unit test for the property 'JmxEnabled'
        }
        /// <summary>
        /// Test the property 'Instances'
        /// </summary>
        [Test]
        public void InstancesTest()
        {
            // TODO unit test for the property 'Instances'
        }
        /// <summary>
        /// Test the property 'StorageBlocks'
        /// </summary>
        [Test]
        public void StorageBlocksTest()
        {
            // TODO unit test for the property 'StorageBlocks'
        }
        /// <summary>
        /// Test the property 'MinimumInstanceCount'
        /// </summary>
        [Test]
        public void MinimumInstanceCountTest()
        {
            // TODO unit test for the property 'MinimumInstanceCount'
        }
        /// <summary>
        /// Test the property 'MaximumInstanceCount'
        /// </summary>
        [Test]
        public void MaximumInstanceCountTest()
        {
            // TODO unit test for the property 'MaximumInstanceCount'
        }
        /// <summary>
        /// Test the property 'HttpMapped'
        /// </summary>
        [Test]
        public void HttpMappedTest()
        {
            // TODO unit test for the property 'HttpMapped'
        }
        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Test]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }
        /// <summary>
        /// Test the property 'ScalingType'
        /// </summary>
        [Test]
        public void ScalingTypeTest()
        {
            // TODO unit test for the property 'ScalingType'
        }
        /// <summary>
        /// Test the property 'IsOperatorOverride'
        /// </summary>
        [Test]
        public void IsOperatorOverrideTest()
        {
            // TODO unit test for the property 'IsOperatorOverride'
        }
        /// <summary>
        /// Test the property 'MonitoringConnectionDetails'
        /// </summary>
        [Test]
        public void MonitoringConnectionDetailsTest()
        {
            // TODO unit test for the property 'MonitoringConnectionDetails'
        }
        /// <summary>
        /// Test the property 'ScalingSchedule'
        /// </summary>
        [Test]
        public void ScalingScheduleTest()
        {
            // TODO unit test for the property 'ScalingSchedule'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'StorageQuota'
        /// </summary>
        [Test]
        public void StorageQuotaTest()
        {
            // TODO unit test for the property 'StorageQuota'
        }
        /// <summary>
        /// Test the property 'ResourcePolicy'
        /// </summary>
        [Test]
        public void ResourcePolicyTest()
        {
            // TODO unit test for the property 'ResourcePolicy'
        }
        /// <summary>
        /// Test the property 'CustomProperties'
        /// </summary>
        [Test]
        public void CustomPropertiesTest()
        {
            // TODO unit test for the property 'CustomProperties'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Test]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
