/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2001DeployedInstances
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2001DeployedInstancesTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2001DeployedInstances
        //private InlineResponse2001DeployedInstances instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2001DeployedInstances
            //instance = new InlineResponse2001DeployedInstances();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2001DeployedInstances
        /// </summary>
        [Test]
        public void InlineResponse2001DeployedInstancesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2001DeployedInstances
            //Assert.IsInstanceOfType<InlineResponse2001DeployedInstances> (instance, "variable 'instance' is a InlineResponse2001DeployedInstances");
        }

        /// <summary>
        /// Test the property 'InstanceAlias'
        /// </summary>
        [Test]
        public void InstanceAliasTest()
        {
            // TODO unit test for the property 'InstanceAlias'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
