/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20018
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20018Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20018
        //private InlineResponse20018 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20018
            //instance = new InlineResponse20018();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20018
        /// </summary>
        [Test]
        public void InlineResponse20018InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20018
            //Assert.IsInstanceOfType<InlineResponse20018> (instance, "variable 'instance' is a InlineResponse20018");
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Test]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }
        /// <summary>
        /// Test the property 'DebugCount'
        /// </summary>
        [Test]
        public void DebugCountTest()
        {
            // TODO unit test for the property 'DebugCount'
        }
        /// <summary>
        /// Test the property 'InfoCount'
        /// </summary>
        [Test]
        public void InfoCountTest()
        {
            // TODO unit test for the property 'InfoCount'
        }
        /// <summary>
        /// Test the property 'WarningCount'
        /// </summary>
        [Test]
        public void WarningCountTest()
        {
            // TODO unit test for the property 'WarningCount'
        }
        /// <summary>
        /// Test the property 'ErrorCount'
        /// </summary>
        [Test]
        public void ErrorCountTest()
        {
            // TODO unit test for the property 'ErrorCount'
        }
        /// <summary>
        /// Test the property 'FatalCount'
        /// </summary>
        [Test]
        public void FatalCountTest()
        {
            // TODO unit test for the property 'FatalCount'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
