/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2008
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2008Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2008
        //private InlineResponse2008 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2008
            //instance = new InlineResponse2008();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2008
        /// </summary>
        [Test]
        public void InlineResponse2008InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2008
            //Assert.IsInstanceOfType<InlineResponse2008> (instance, "variable 'instance' is a InlineResponse2008");
        }

        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'StorageQuota'
        /// </summary>
        [Test]
        public void StorageQuotaTest()
        {
            // TODO unit test for the property 'StorageQuota'
        }
        /// <summary>
        /// Test the property 'ResourcePolicy'
        /// </summary>
        [Test]
        public void ResourcePolicyTest()
        {
            // TODO unit test for the property 'ResourcePolicy'
        }
        /// <summary>
        /// Test the property 'CustomProperties'
        /// </summary>
        [Test]
        public void CustomPropertiesTest()
        {
            // TODO unit test for the property 'CustomProperties'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Test]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
