/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MonitoringSubscription1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MonitoringSubscription1Tests
    {
        // TODO uncomment below to declare an instance variable for MonitoringSubscription1
        //private MonitoringSubscription1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MonitoringSubscription1
            //instance = new MonitoringSubscription1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MonitoringSubscription1
        /// </summary>
        [Test]
        public void MonitoringSubscription1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MonitoringSubscription1
            //Assert.IsInstanceOfType<MonitoringSubscription1> (instance, "variable 'instance' is a MonitoringSubscription1");
        }

        /// <summary>
        /// Test the property 'Locator'
        /// </summary>
        [Test]
        public void LocatorTest()
        {
            // TODO unit test for the property 'Locator'
        }
        /// <summary>
        /// Test the property 'Component'
        /// </summary>
        [Test]
        public void ComponentTest()
        {
            // TODO unit test for the property 'Component'
        }
        /// <summary>
        /// Test the property 'UpdateInterval'
        /// </summary>
        [Test]
        public void UpdateIntervalTest()
        {
            // TODO unit test for the property 'UpdateInterval'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
