/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PagedResourceBaseSubscribedTenant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PagedResourceBaseSubscribedTenantTests
    {
        // TODO uncomment below to declare an instance variable for PagedResourceBaseSubscribedTenant
        //private PagedResourceBaseSubscribedTenant instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PagedResourceBaseSubscribedTenant
            //instance = new PagedResourceBaseSubscribedTenant();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PagedResourceBaseSubscribedTenant
        /// </summary>
        [Test]
        public void PagedResourceBaseSubscribedTenantInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PagedResourceBaseSubscribedTenant
            //Assert.IsInstanceOfType<PagedResourceBaseSubscribedTenant> (instance, "variable 'instance' is a PagedResourceBaseSubscribedTenant");
        }

        /// <summary>
        /// Test the property 'CurrentPage'
        /// </summary>
        [Test]
        public void CurrentPageTest()
        {
            // TODO unit test for the property 'CurrentPage'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Test]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Test]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
        /// <summary>
        /// Test the property 'TotalItems'
        /// </summary>
        [Test]
        public void TotalItemsTest()
        {
            // TODO unit test for the property 'TotalItems'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Test]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
        /// <summary>
        /// Test the property 'PreviousPage'
        /// </summary>
        [Test]
        public void PreviousPageTest()
        {
            // TODO unit test for the property 'PreviousPage'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
