/* 
 * Account Management REST API
 *
 * The Account Management REST API can be used to manage user accounts, roles, and securables for applications on the Platform. The endpoints of this API allow you to perform the same the functionality of the Platform's Account Portal for your Tenant's applications.   For more information, see our documentation on the [Account Portal](/current/account).     ## Authentication    Before making a request, you must be authenticated. Follow these instuctions [to get authenticated](/restapi/accountmanagement/v1/authentication). ## Making a Request   ### Prerequisites    * Installed Platform of version 6.6.0 or later    * An active user account assigned to an active Tenant Account or Developer Team    * Authentication token   ### Request URL    All requests must use **https**.       The URL for every request you make is the URL of your Platform followed by \"/account\" and the path structure of the endpoint. For example, if your Platform URL is https://apps.apprenda.harp and you want to get a list of all user accounts for your Tenant, the request URL will be https://apps.apprenda.harp/account/api/v1/users.     For more information, see our documentation on [using api resources](/restapi/accountmanagement/v1/using-resources) and [finding your Cloud URI](/current/clouduri).    ### Request Headers  Your authenication token must be passed in the header of all requests using the key **ApprendaSessionToken** (not case sensitive).    
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ApplicationVersion
    /// </summary>
    [DataContract]
    public partial class ApplicationVersion :  IEquatable<ApplicationVersion>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Stage
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StageEnum
        {
            
            /// <summary>
            /// Enum Published for "Published"
            /// </summary>
            [EnumMember(Value = "Published")]
            Published,
            
            /// <summary>
            /// Enum Sandbox for "Sandbox"
            /// </summary>
            [EnumMember(Value = "Sandbox")]
            Sandbox
        }

        /// <summary>
        /// Gets or Sets Stage
        /// </summary>
        [DataMember(Name="stage", EmitDefaultValue=false)]
        public StageEnum? Stage { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationVersion" /> class.
        /// </summary>
        /// <param name="ProviderName">ProviderName.</param>
        /// <param name="ApplicationAlias">ApplicationAlias.</param>
        /// <param name="ApplicationDescription">ApplicationDescription.</param>
        /// <param name="ApplicationName">ApplicationName.</param>
        /// <param name="VersionAlias">VersionAlias.</param>
        /// <param name="Stage">Stage.</param>
        /// <param name="Plans">Plans.</param>
        /// <param name="Securables">Securables.</param>
        /// <param name="Href">Href.</param>
        public ApplicationVersion(string ProviderName = default(string), string ApplicationAlias = default(string), string ApplicationDescription = default(string), string ApplicationName = default(string), string VersionAlias = default(string), StageEnum? Stage = default(StageEnum?), ResourceBase Plans = default(ResourceBase), ResourceBase Securables = default(ResourceBase), string Href = default(string))
        {
            this.ProviderName = ProviderName;
            this.ApplicationAlias = ApplicationAlias;
            this.ApplicationDescription = ApplicationDescription;
            this.ApplicationName = ApplicationName;
            this.VersionAlias = VersionAlias;
            this.Stage = Stage;
            this.Plans = Plans;
            this.Securables = Securables;
            this.Href = Href;
        }
        
        /// <summary>
        /// Gets or Sets ProviderName
        /// </summary>
        [DataMember(Name="providerName", EmitDefaultValue=false)]
        public string ProviderName { get; set; }
        /// <summary>
        /// Gets or Sets ApplicationAlias
        /// </summary>
        [DataMember(Name="applicationAlias", EmitDefaultValue=false)]
        public string ApplicationAlias { get; set; }
        /// <summary>
        /// Gets or Sets ApplicationDescription
        /// </summary>
        [DataMember(Name="applicationDescription", EmitDefaultValue=false)]
        public string ApplicationDescription { get; set; }
        /// <summary>
        /// Gets or Sets ApplicationName
        /// </summary>
        [DataMember(Name="applicationName", EmitDefaultValue=false)]
        public string ApplicationName { get; set; }
        /// <summary>
        /// Gets or Sets VersionAlias
        /// </summary>
        [DataMember(Name="versionAlias", EmitDefaultValue=false)]
        public string VersionAlias { get; set; }
        /// <summary>
        /// Gets or Sets Plans
        /// </summary>
        [DataMember(Name="plans", EmitDefaultValue=false)]
        public ResourceBase Plans { get; set; }
        /// <summary>
        /// Gets or Sets Securables
        /// </summary>
        [DataMember(Name="securables", EmitDefaultValue=false)]
        public ResourceBase Securables { get; set; }
        /// <summary>
        /// Gets or Sets Href
        /// </summary>
        [DataMember(Name="href", EmitDefaultValue=false)]
        public string Href { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApplicationVersion {\n");
            sb.Append("  ProviderName: ").Append(ProviderName).Append("\n");
            sb.Append("  ApplicationAlias: ").Append(ApplicationAlias).Append("\n");
            sb.Append("  ApplicationDescription: ").Append(ApplicationDescription).Append("\n");
            sb.Append("  ApplicationName: ").Append(ApplicationName).Append("\n");
            sb.Append("  VersionAlias: ").Append(VersionAlias).Append("\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("  Plans: ").Append(Plans).Append("\n");
            sb.Append("  Securables: ").Append(Securables).Append("\n");
            sb.Append("  Href: ").Append(Href).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ApplicationVersion);
        }

        /// <summary>
        /// Returns true if ApplicationVersion instances are equal
        /// </summary>
        /// <param name="other">Instance of ApplicationVersion to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApplicationVersion other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ProviderName == other.ProviderName ||
                    this.ProviderName != null &&
                    this.ProviderName.Equals(other.ProviderName)
                ) && 
                (
                    this.ApplicationAlias == other.ApplicationAlias ||
                    this.ApplicationAlias != null &&
                    this.ApplicationAlias.Equals(other.ApplicationAlias)
                ) && 
                (
                    this.ApplicationDescription == other.ApplicationDescription ||
                    this.ApplicationDescription != null &&
                    this.ApplicationDescription.Equals(other.ApplicationDescription)
                ) && 
                (
                    this.ApplicationName == other.ApplicationName ||
                    this.ApplicationName != null &&
                    this.ApplicationName.Equals(other.ApplicationName)
                ) && 
                (
                    this.VersionAlias == other.VersionAlias ||
                    this.VersionAlias != null &&
                    this.VersionAlias.Equals(other.VersionAlias)
                ) && 
                (
                    this.Stage == other.Stage ||
                    this.Stage != null &&
                    this.Stage.Equals(other.Stage)
                ) && 
                (
                    this.Plans == other.Plans ||
                    this.Plans != null &&
                    this.Plans.Equals(other.Plans)
                ) && 
                (
                    this.Securables == other.Securables ||
                    this.Securables != null &&
                    this.Securables.Equals(other.Securables)
                ) && 
                (
                    this.Href == other.Href ||
                    this.Href != null &&
                    this.Href.Equals(other.Href)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ProviderName != null)
                    hash = hash * 59 + this.ProviderName.GetHashCode();
                if (this.ApplicationAlias != null)
                    hash = hash * 59 + this.ApplicationAlias.GetHashCode();
                if (this.ApplicationDescription != null)
                    hash = hash * 59 + this.ApplicationDescription.GetHashCode();
                if (this.ApplicationName != null)
                    hash = hash * 59 + this.ApplicationName.GetHashCode();
                if (this.VersionAlias != null)
                    hash = hash * 59 + this.VersionAlias.GetHashCode();
                if (this.Stage != null)
                    hash = hash * 59 + this.Stage.GetHashCode();
                if (this.Plans != null)
                    hash = hash * 59 + this.Plans.GetHashCode();
                if (this.Securables != null)
                    hash = hash * 59 + this.Securables.GetHashCode();
                if (this.Href != null)
                    hash = hash * 59 + this.Href.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
