/* 
 * Account Management REST API
 *
 * The Account Management REST API can be used to manage user accounts, roles, and securables for applications on the Platform. The endpoints of this API allow you to perform the same the functionality of the Platform's Account Portal for your Tenant's applications.   For more information, see our documentation on the [Account Portal](/current/account).     ## Authentication    Before making a request, you must be authenticated. Follow these instuctions [to get authenticated](/restapi/accountmanagement/v1/authentication). ## Making a Request   ### Prerequisites    * Installed Platform of version 6.6.0 or later    * An active user account assigned to an active Tenant Account or Developer Team    * Authentication token   ### Request URL    All requests must use **https**.       The URL for every request you make is the URL of your Platform followed by \"/account\" and the path structure of the endpoint. For example, if your Platform URL is https://apps.apprenda.harp and you want to get a list of all user accounts for your Tenant, the request URL will be https://apps.apprenda.harp/account/api/v1/users.     For more information, see our documentation on [using api resources](/restapi/accountmanagement/v1/using-resources) and [finding your Cloud URI](/current/clouduri).    ### Request Headers  Your authenication token must be passed in the header of all requests using the key **ApprendaSessionToken** (not case sensitive).    
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Request to create a number of subscriptions for the given plan
    /// </summary>
    [DataContract]
    public partial class PlanRequest :  IEquatable<PlanRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlanRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanRequest" /> class.
        /// </summary>
        /// <param name="PlanId">PlanId (required).</param>
        /// <param name="NumberOfSubscriptions">NumberOfSubscriptions.</param>
        public PlanRequest(Guid? PlanId = default(Guid?), int? NumberOfSubscriptions = default(int?))
        {
            // to ensure "PlanId" is required (not null)
            if (PlanId == null)
            {
                throw new InvalidDataException("PlanId is a required property for PlanRequest and cannot be null");
            }
            else
            {
                this.PlanId = PlanId;
            }
            this.NumberOfSubscriptions = NumberOfSubscriptions;
        }
        
        /// <summary>
        /// Gets or Sets PlanId
        /// </summary>
        [DataMember(Name="planId", EmitDefaultValue=false)]
        public Guid? PlanId { get; set; }
        /// <summary>
        /// Gets or Sets NumberOfSubscriptions
        /// </summary>
        [DataMember(Name="numberOfSubscriptions", EmitDefaultValue=false)]
        public int? NumberOfSubscriptions { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlanRequest {\n");
            sb.Append("  PlanId: ").Append(PlanId).Append("\n");
            sb.Append("  NumberOfSubscriptions: ").Append(NumberOfSubscriptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PlanRequest);
        }

        /// <summary>
        /// Returns true if PlanRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of PlanRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlanRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.PlanId == other.PlanId ||
                    this.PlanId != null &&
                    this.PlanId.Equals(other.PlanId)
                ) && 
                (
                    this.NumberOfSubscriptions == other.NumberOfSubscriptions ||
                    this.NumberOfSubscriptions != null &&
                    this.NumberOfSubscriptions.Equals(other.NumberOfSubscriptions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.PlanId != null)
                    hash = hash * 59 + this.PlanId.GetHashCode();
                if (this.NumberOfSubscriptions != null)
                    hash = hash * 59 + this.NumberOfSubscriptions.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
