/* 
 * Apprenda.DeveloperPortal.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IVersionReportCardsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>List&lt;ReportCard&gt;</returns>
        List<ReportCard> VersionReportCardsGet (string appAlias, string versionAlias);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>ApiResponse of List&lt;ReportCard&gt;</returns>
        ApiResponse<List<ReportCard>> VersionReportCardsGetWithHttpInfo (string appAlias, string versionAlias);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>List&lt;ReportCard&gt;</returns>
        List<ReportCard> VersionReportCardsGetLatest (string appAlias, string versionAlias);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>ApiResponse of List&lt;ReportCard&gt;</returns>
        ApiResponse<List<ReportCard>> VersionReportCardsGetLatestWithHttpInfo (string appAlias, string versionAlias);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>Task of List&lt;ReportCard&gt;</returns>
        System.Threading.Tasks.Task<List<ReportCard>> VersionReportCardsGetAsync (string appAlias, string versionAlias);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>Task of ApiResponse (List&lt;ReportCard&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ReportCard>>> VersionReportCardsGetAsyncWithHttpInfo (string appAlias, string versionAlias);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>Task of List&lt;ReportCard&gt;</returns>
        System.Threading.Tasks.Task<List<ReportCard>> VersionReportCardsGetLatestAsync (string appAlias, string versionAlias);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>Task of ApiResponse (List&lt;ReportCard&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ReportCard>>> VersionReportCardsGetLatestAsyncWithHttpInfo (string appAlias, string versionAlias);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class VersionReportCardsApi : IVersionReportCardsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="VersionReportCardsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public VersionReportCardsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VersionReportCardsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public VersionReportCardsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>List&lt;ReportCard&gt;</returns>
        public List<ReportCard> VersionReportCardsGet (string appAlias, string versionAlias)
        {
             ApiResponse<List<ReportCard>> localVarResponse = VersionReportCardsGetWithHttpInfo(appAlias, versionAlias);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>ApiResponse of List&lt;ReportCard&gt;</returns>
        public ApiResponse< List<ReportCard> > VersionReportCardsGetWithHttpInfo (string appAlias, string versionAlias)
        {
            // verify the required parameter 'appAlias' is set
            if (appAlias == null)
                throw new ApiException(400, "Missing required parameter 'appAlias' when calling VersionReportCardsApi->VersionReportCardsGet");
            // verify the required parameter 'versionAlias' is set
            if (versionAlias == null)
                throw new ApiException(400, "Missing required parameter 'versionAlias' when calling VersionReportCardsApi->VersionReportCardsGet");

            var localVarPath = "/api/v1/versions/{appAlias}/{versionAlias}/reportCards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (appAlias != null) localVarPathParams.Add("appAlias", Configuration.ApiClient.ParameterToString(appAlias)); // path parameter
            if (versionAlias != null) localVarPathParams.Add("versionAlias", Configuration.ApiClient.ParameterToString(versionAlias)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("VersionReportCardsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ReportCard>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ReportCard>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ReportCard>)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>Task of List&lt;ReportCard&gt;</returns>
        public async System.Threading.Tasks.Task<List<ReportCard>> VersionReportCardsGetAsync (string appAlias, string versionAlias)
        {
             ApiResponse<List<ReportCard>> localVarResponse = await VersionReportCardsGetAsyncWithHttpInfo(appAlias, versionAlias);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>Task of ApiResponse (List&lt;ReportCard&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ReportCard>>> VersionReportCardsGetAsyncWithHttpInfo (string appAlias, string versionAlias)
        {
            // verify the required parameter 'appAlias' is set
            if (appAlias == null)
                throw new ApiException(400, "Missing required parameter 'appAlias' when calling VersionReportCardsApi->VersionReportCardsGet");
            // verify the required parameter 'versionAlias' is set
            if (versionAlias == null)
                throw new ApiException(400, "Missing required parameter 'versionAlias' when calling VersionReportCardsApi->VersionReportCardsGet");

            var localVarPath = "/api/v1/versions/{appAlias}/{versionAlias}/reportCards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (appAlias != null) localVarPathParams.Add("appAlias", Configuration.ApiClient.ParameterToString(appAlias)); // path parameter
            if (versionAlias != null) localVarPathParams.Add("versionAlias", Configuration.ApiClient.ParameterToString(versionAlias)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("VersionReportCardsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ReportCard>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ReportCard>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ReportCard>)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>List&lt;ReportCard&gt;</returns>
        public List<ReportCard> VersionReportCardsGetLatest (string appAlias, string versionAlias)
        {
             ApiResponse<List<ReportCard>> localVarResponse = VersionReportCardsGetLatestWithHttpInfo(appAlias, versionAlias);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>ApiResponse of List&lt;ReportCard&gt;</returns>
        public ApiResponse< List<ReportCard> > VersionReportCardsGetLatestWithHttpInfo (string appAlias, string versionAlias)
        {
            // verify the required parameter 'appAlias' is set
            if (appAlias == null)
                throw new ApiException(400, "Missing required parameter 'appAlias' when calling VersionReportCardsApi->VersionReportCardsGetLatest");
            // verify the required parameter 'versionAlias' is set
            if (versionAlias == null)
                throw new ApiException(400, "Missing required parameter 'versionAlias' when calling VersionReportCardsApi->VersionReportCardsGetLatest");

            var localVarPath = "/api/v1/versions/{appAlias}/{versionAlias}/reportCards/latest";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (appAlias != null) localVarPathParams.Add("appAlias", Configuration.ApiClient.ParameterToString(appAlias)); // path parameter
            if (versionAlias != null) localVarPathParams.Add("versionAlias", Configuration.ApiClient.ParameterToString(versionAlias)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("VersionReportCardsGetLatest", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ReportCard>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ReportCard>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ReportCard>)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>Task of List&lt;ReportCard&gt;</returns>
        public async System.Threading.Tasks.Task<List<ReportCard>> VersionReportCardsGetLatestAsync (string appAlias, string versionAlias)
        {
             ApiResponse<List<ReportCard>> localVarResponse = await VersionReportCardsGetLatestAsyncWithHttpInfo(appAlias, versionAlias);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appAlias"></param>
        /// <param name="versionAlias"></param>
        /// <returns>Task of ApiResponse (List&lt;ReportCard&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ReportCard>>> VersionReportCardsGetLatestAsyncWithHttpInfo (string appAlias, string versionAlias)
        {
            // verify the required parameter 'appAlias' is set
            if (appAlias == null)
                throw new ApiException(400, "Missing required parameter 'appAlias' when calling VersionReportCardsApi->VersionReportCardsGetLatest");
            // verify the required parameter 'versionAlias' is set
            if (versionAlias == null)
                throw new ApiException(400, "Missing required parameter 'versionAlias' when calling VersionReportCardsApi->VersionReportCardsGetLatest");

            var localVarPath = "/api/v1/versions/{appAlias}/{versionAlias}/reportCards/latest";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (appAlias != null) localVarPathParams.Add("appAlias", Configuration.ApiClient.ParameterToString(appAlias)); // path parameter
            if (versionAlias != null) localVarPathParams.Add("versionAlias", Configuration.ApiClient.ParameterToString(versionAlias)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("VersionReportCardsGetLatest", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ReportCard>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ReportCard>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ReportCard>)));
            
        }

    }
}
